Document: lesewerkstatt
Title: Debian lesewerkstatt Manual
Author: <insert document author here>
Abstract: This manual describes what lesewerkstatt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lesewerkstatt/lesewerkstatt.sgml.gz

Format: postscript
Files: /usr/share/doc/lesewerkstatt/lesewerkstatt.ps.gz

Format: text
Files: /usr/share/doc/lesewerkstatt/lesewerkstatt.text.gz

Format: HTML
Index: /usr/share/doc/lesewerkstatt/html/index.html
Files: /usr/share/doc/lesewerkstatt/html/*.html
